Contao 3.5.20
contao/core pull request #8598
Opened 2016-12-15 16:01 UTC by leofeyer

2016-12-15 16:44 UTC, discordier approved these changes
LGTM :+1:

2016-12-15 16:58 UTC, aschempp requested changes

2016-12-15 16:58 UTC, aschempp commented on system/modules/core/library/Contao/Encryption.php
> +		@trigger_error('Using Encryption::decrypt() has been deprecated and will no longer work in Contao 5.0. Use the DCA load and save callbacks to implement your own encryption routines.', E_USER_DEPREC
This message is misleading, because the methods are not related to the DCA

2016-12-15 19:17 UTC, leofeyer commented on system/modules/core/library/Contao/Encryption.php
> +		@trigger_error('Using Encryption::decrypt() has been deprecated and will no longer work in Contao 5.0. Use the DCA load and save callbacks to implement your own encryption routines.', E_USER_DEPREC
The load and save callbacks are not related to the DCA?

2016-12-15 19:53 UTC, discordier commented on system/modules/core/library/Contao/Encryption.php
> +		@trigger_error('Using Encryption::decrypt() has been deprecated and will no longer work in Contao 5.0. Use the DCA load and save callbacks to implement your own encryption routines.', E_USER_DEPREC
He is talking about the `\Encryption` class in general and it's methods.

2016-12-15 19:55 UTC, leofeyer commented on system/modules/core/library/Contao/Encryption.php
> +		@trigger_error('Using Encryption::decrypt() has been deprecated and will no longer work in Contao 5.0. Use the DCA load and save callbacks to implement your own encryption routines.', E_USER_DEPREC
Ah, I see. So what do you suggest then?

2016-12-15 19:57 UTC, discordier commented on system/modules/core/library/Contao/Encryption.php
> +		@trigger_error('Using Encryption::decrypt() has been deprecated and will no longer work in Contao 5.0. Use the DCA load and save callbacks to implement your own encryption routines.', E_USER_DEPREC
Why not simply omitting the mentioning of DCa at all?
"Using Encryption::decrypt() has been deprecated and will no longer work in Contao 5.0. Implement your own encryption routines."

We could also write a chapter in the `UPGRADING.md` dedicated to the overall issue and explaining the reasons of the deprecation and simply pass this link into the message.

2016-12-16 07:40 UTC, aschempp commented on system/modules/core/library/Contao/Encryption.php
> +		@trigger_error('Using Encryption::decrypt() has been deprecated and will no longer work in Contao 5.0. Use the DCA load and save callbacks to implement your own encryption routines.', E_USER_DEPREC
I'm fine with @discordier's message. Though as mentioned in the respective ticket, people won't know where the message is coming from…

2016-12-16 07:59 UTC, leofeyer commented
All comments have been addressed. Please review again.

2016-12-16 08:04 UTC, aschempp approved these changes

2016-12-16 08:14 UTC, ausi approved these changes

2016-12-16 08:41 UTC, Toflar approved these changes

2016-12-16 08:41 UTC, Toflar commented on system/modules/core/library/Contao/Encryption.php
> +	 * @deprecated Deprecated since Contao 3.5, to be removed in Contao 5.
This message feels really wrong to me. Please **NEVER** implement your own encryption routine but use existing and tested libraries for this :-) The message as it is now implies you should invent something on your own :-D

2016-12-16 08:41 UTC, Toflar commented on system/modules/core/library/Contao/Widget.php
> +			@trigger_error('Using the "encrypt" flag' . (!empty($strTable) && !empty($strField) ? ' on ' . $strTable . '.' . $strField : '') . ' has been deprecated and will no longer work in Contao 5.0. Use
Same here, please adjust to something like `Use well tested third party libraries such as phpseclib`.

2016-12-16 09:06 UTC, leofeyer commented
The release has been scheduled for Monday, December 19th.

2016-12-19 10:26 UTC, ausi approved these changes

2016-12-19 13:08 UTC, merged