fix cache key usage
contao/core pull request #8695
Opened 2017-04-08 08:15 UTC by fritzmg

This fixes #8694.

Explanation:

* The `Automator` uses `$objPages->dns ?: '*'` [here](https://github.com/contao/core/blob/3.5.25/system/modules/core/library/Contao/Automator.php#L539) for creating the mappings of the empty request cache key.
* However, `FrontendTemplate::addToCache` never actually uses `*` when creating the cache key, see [here](https://github.com/contao/core/blob/3.5.25/system/modules/core/classes/FrontendTemplate.php#L216). Thus the cache key for the empty request will always be `example.org/empty…`.
* Thus `FrontendIndex::outputFromCache` never actually finds a cache entry for the empty request [here](https://github.com/contao/core/blob/3.5.25/system/modules/core/controllers/FrontendIndex.php#L318-L431) since it will always be looking for `*/empty…`, if no DNS setting was made in the root page.

2017-04-08 08:23 UTC, fritzmg commented on system/modules/core/classes/FrontendTemplate.php
> +				ltrim($strCacheKey, '*'),
Just to comment on why this is necessary: when the cache key starts with `*`, the resulting PHP header of the cache file would look like this:
```php
<?php /* */empty.de */ $expire = 1494230344; $content = 'text/html'; $type = 'regular'; $files = ''; $assets = ''; ?>
```
This is invalid PHP syntax of course, thus I simply remove the `*` for the header.

2017-04-18 09:57 UTC, leofeyer requested changes

2017-04-18 09:57 UTC, leofeyer commented on system/modules/core/classes/FrontendTemplate.php
> +				$strCacheKey = ($objPage->domain ?: '*') . '/empty.' . $objPage->language;
Shouldn't this be `$objPage->dns`?

2017-04-18 09:57 UTC, leofeyer commented on system/modules/core/classes/FrontendTemplate.php
> +				ltrim($strCacheKey, '*'),
How about `"<?php\n\n// %s\n\$expire = %d;\n\$content = %s;\n\$type = %s;\n\$files = %s;\n\$assets = %s;\n\n?>\n"` instead?

2017-04-18 09:59 UTC, fritzmg commented on system/modules/core/classes/FrontendTemplate.php
> +				$strCacheKey = ($objPage->domain ?: '*') . '/empty.' . $objPage->language;
No, `$objPage->dns` is only set for root pages. For other pages this information is saves in `->domain`. See [system/modules/core/models/PageModel.php#L868](https://github.com/contao/core/blob/3.5.25/system/modules/core/models/PageModel.php#L868)

2017-04-18 10:01 UTC, fritzmg commented
> How about "<?php\n\n// %s\n\$expire = %d;\n\$content = %s;\n\$type = %s;\n\$files = %s;\n\$assets = %s;\n\n?>\n" instead?

Sure, that should work too :)

2017-04-18 10:04 UTC, fritzmg commented on system/modules/core/classes/FrontendTemplate.php
> +				ltrim($strCacheKey, '*'),
Sure, that should work too :). Should even work without the line breaks, I think.

2017-04-18 10:18 UTC, fritzmg commented on system/modules/core/classes/FrontendTemplate.php
> +				ltrim($strCacheKey, '*'),
I have changed it now.

2017-04-18 10:51 UTC, leofeyer approved these changes

2017-04-18 12:01 UTC, leofeyer approved these changes

2017-04-18 12:02 UTC, merged